# SPDX-FileCopyrightText: 2026 The herdr-bridge Authors
#
# SPDX-License-Identifier: Apache-2.0

"""acp.adapter integration tests (docs/acpx-adapter-implementation-plan.md
§2.2).

Runs the full config -> argv -> env -> spawn -> real-behavior-assertion
end-to-end path, using a real local acpx + a patched opencode binary
(`.vendor/opencode-patched/`) + real model credentials. `skip`ped in CI for
lack of the local binary/credentials (see the `integration` marker in
`pyproject.toml`; `ci.yml` uses `-m "not integration"`).

**Shared fixture (PPLX C1)**: `agent_binary` always points, via a symlink, at
a scratch directory whose name contains a space, so every test that runs the
real acpx pipeline also proves that acpx's actual tokenizer correctly
round-trips Python `shlex.quote()`'s output.

**Design adjustment for test 2 (an adversarial fix made during
implementation, not a PPLX review item)**: the v3 plan document originally
envisioned using `deny-all` (`"*":"deny"`) to test "child session doesn't
deadlock". Reading opencode's `permission/index.ts` `ask()` directly revealed
that the `"deny"` verdict goes entirely through a local synchronous path
(`if (rule.action === "deny") return yield* new
PermissionV1.DeniedError(...)`), never creating a `Deferred` and never
emitting a `permission.asked` event — G1's code path only triggers on an
`"ask"` verdict. Testing "no deadlock" with `deny-all` is structurally
vacuous: regardless of whether G1 has regressed, this test would necessarily
pass, because it never actually reaches the path that could hang. Instead we
use `approve-reads` (`"*":"ask"`) plus delegating to a subtask, where the
subtask itself attempts a write (not on the read/glob/grep/list allowlist, so
it falls through to `"*":"ask"`) — this is the path that genuinely creates a
`Deferred`, emits the ACP `session/request_permission`, and requires G1's
`resolveAncestor` to correctly map it back to the registered root session.
Paired with acpx's `--approve-all`, so that the ask generated by creating the
task itself isn't blocked by the non-interactive default (`deny`), letting us
actually observe the subtask being spawned and the full
ask->resolve->response cycle completing.

**Scoping decision for the MCP-tool gap**: test 1 only verifies that a native
write is blocked by `"*":"deny"`; it doesn't additionally spin up a real MCP
filesystem server for a live re-check. The guarantee that `"*"` also applies
to MCP tools (which use the tool's own name as the permission key) comes from
the mechanism itself — `Wildcard.match()` doing a wildcard match against any
permission name (confirmed by directly reading
`packages/opencode/src/session/tools.ts:390-408`) — not from native and MCP
tools going through two separate code paths. Spinning up a real MCP server
would only re-verify a mechanism already confirmed by reading the source, and
wouldn't catch any regression unique to either native or MCP tools, so it's
out of scope for this round.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

import pytest

from herdr_bridge.acp.adapter import (
    build_acpx_argv_and_env,
    build_acpx_policy_flags,
    resolve_patched_opencode_binary,
    write_session_config,
)
from herdr_bridge.acp.errors import AcpAdapterError
from herdr_bridge.acp.events import extract_final_result, parse_stream
from herdr_bridge.acp.models import AcpPolicy

pytestmark = pytest.mark.integration

_REPO_ROOT = Path(__file__).resolve().parent.parent
_VENDOR_DIR = _REPO_ROOT / ".vendor" / "opencode-patched"
_MODEL_ID = "opencode/deepseek-v4-flash-free"


def _resolve_patched_binary() -> Path | None:
    try:
        path, _warnings = resolve_patched_opencode_binary(_VENDOR_DIR)
    except AcpAdapterError:
        return None
    return path if path.exists() and os.access(path, os.X_OK) else None


_PATCHED_BINARY = _resolve_patched_binary()


def _has_real_environment() -> bool:
    """Whether the locally-built patched binary and real model credentials
    are both in place."""
    if _PATCHED_BINARY is None:
        return False
    try:
        result = subprocess.run(
            [str(_PATCHED_BINARY), "models"],
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0 and _MODEL_ID in result.stdout


requires_real_environment = pytest.mark.skipif(
    not _has_real_environment(),
    reason=(
        "requires the local patched opencode binary (.vendor/opencode-patched/) "
        "and real model credentials — see MANIFEST.json"
    ),
)


def _agent_binary_with_space(scratch_root: Path) -> Path:
    """A symlink to a path containing a space (PPLX C1: proof of acpx
    tokenizer's real round-trip behavior)."""
    space_dir = scratch_root / "opencode patched"
    space_dir.mkdir()
    link = space_dir / "opencode"
    link.symlink_to(_PATCHED_BINARY)
    return link


def _run_acpx_prompt(
    *,
    scratch_root: Path,
    workdir: Path,
    policy: AcpPolicy,
    prompt: str,
    timeout: int,
    extra_acpx_args: list[str] | None = None,
):
    session_dir = scratch_root / "session"
    session_dir.mkdir(exist_ok=True)
    config_path = write_session_config(policy, session_dir=session_dir)
    agent_binary = _agent_binary_with_space(scratch_root)

    base_argv, env = build_acpx_argv_and_env(agent="opencode", agent_binary=agent_binary, config_path=config_path, cwd=workdir)

    # Isolate from the developer's own global opencode config (`~/.config/opencode/`)
    # so tests exercise opencode's real built-in "build" agent, not any personal
    # custom agent/plugin setup (discovered the hard way: this machine's global
    # config replaces the default agent entirely, forcing every prompt through an
    # unrelated task-delegating persona). `OPENCODE_TEST_HOME`/`HOME` redirection
    # is the same isolation hook opencode's own test harness uses
    # (`packages/core/src/global.ts`: `Path.home` reads `OPENCODE_TEST_HOME` first).
    fake_home = scratch_root / "fake-home"
    fake_home.mkdir(exist_ok=True)
    env = {**env, "HOME": str(fake_home), "OPENCODE_TEST_HOME": str(fake_home)}

    # acpx keeps a detached background "queue-owner" process (+ the underlying
    # opencode subprocess) alive per session for `--ttl` seconds after the CLI
    # command returns (default 300s) — found the hard way when repeated manual
    # debugging runs left a pile of these running. `--ttl 5` makes them clean
    # themselves up almost immediately instead of lingering for 5 minutes each.
    #
    # N4 defense-in-depth: always pin --non-interactive-permissions deny (not
    # reliant on this machine's own ~/.acpx/config.json), plus the mode-specific
    # acpx flag (approve-all/deny-all; approve-reads deliberately gets none —
    # see build_acpx_policy_flags). `extra_acpx_args` can still add/override
    # flags per-test (e.g. test 2 needs --approve-all on top of approve-reads'
    # default to let subagent creation through) — --approve-all/--deny-all are
    # mutually exclusive with each other in acpx, so don't combine an
    # extra_acpx_args override with a policy whose default already sets the
    # other one.
    base_argv = [*base_argv, "--ttl", "5", *build_acpx_policy_flags(policy)]

    # acpx's bare one-shot prompt form does a directory-walk lookup for an
    # *existing* session and throws NO_SESSION (code -32002) instead of
    # auto-creating one — confirmed by reading `findRoutedSessionOrThrow` in
    # acpx's own cli.js. `sessions ensure` must be run first against the same
    # (agentCommand, cwd) pair so the later prompt call can find it.
    ensure = subprocess.run(
        [*base_argv, "sessions", "ensure"],
        cwd=workdir,
        env=env,
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    assert ensure.returncode == 0, f"sessions ensure failed: {ensure.stdout}\n{ensure.stderr}"

    argv = [
        *base_argv,
        "--format",
        "json",
        "--model",
        _MODEL_ID,
        "--timeout",
        str(timeout),
        *(extra_acpx_args or []),
        prompt,
    ]

    result = subprocess.run(
        argv,
        cwd=workdir,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout + 30,
        check=False,
    )
    events = list(parse_stream(result.stdout.splitlines()))
    return result, events


@requires_real_environment
class TestDenyAllBlocksNativeWrite:
    def test_deny_all_blocks_native_write_tool(self, tmp_path: Path):
        workdir = tmp_path / "workdir"
        workdir.mkdir()

        result, events = _run_acpx_prompt(
            scratch_root=tmp_path,
            workdir=workdir,
            policy=AcpPolicy(mode="deny-all"),
            prompt=(
                "Use the write tool right now to create a file named canary.txt "
                "in the current directory with the exact content 'blocked'. "
                "Do this immediately without asking for confirmation."
            ),
            timeout=25,
        )

        assert not (workdir / "canary.txt").exists(), (
            f"write should have been blocked by permission.*=deny; stdout tail:\n{result.stdout[-2000:]}"
        )
        final = extract_final_result(events)
        assert final is not None, "call should complete (not hang) even though the write is denied"


@requires_real_environment
class TestG1ChildSessionPermissionDoesNotHang:
    def test_subagent_write_ask_resolves_instead_of_hanging(self, tmp_path: Path):
        workdir = tmp_path / "workdir"
        workdir.mkdir()

        result, events = _run_acpx_prompt(
            scratch_root=tmp_path,
            workdir=workdir,
            policy=AcpPolicy(mode="approve-reads"),
            prompt=(
                "You must use the `task` tool to delegate to a general subagent. "
                "Instruct the subagent to use the write tool to create a file named "
                "child.txt with the content 'from-subagent'. Do not write the file "
                "yourself directly - actually invoke the task tool."
            ),
            timeout=45,
            extra_acpx_args=["--approve-all"],
        )

        final = extract_final_result(events)
        assert final is not None, (
            f"call must complete instead of hanging (G1 regression); stdout tail:\n{result.stdout[-3000:]}"
        )

        permission_asks = [e for e in events if e.type == "session/request_permission"]
        assert permission_asks, (
            "expected at least one real session/request_permission round trip "
            "(proves the ask was not silently dropped)"
        )

        session_ids = {e.session_id for e in events if e.session_id}
        assert len(session_ids) >= 2, (
            "expected both the root session id and the delegated subagent's own "
            "session id to appear in the event stream - a single id suggests the "
            "subagent was never actually spawned, or its identity was collapsed "
            f"into the root's. session ids seen: {session_ids}"
        )


@requires_real_environment
class TestApproveReadsAllowsReadBlocksWrite:
    def test_read_allowed_write_blocked(self, tmp_path: Path):
        workdir = tmp_path / "workdir"
        workdir.mkdir()
        marker = "MARKER-9f3a2b-existing-content"
        (workdir / "existing.txt").write_text(marker)

        result, events = _run_acpx_prompt(
            scratch_root=tmp_path,
            workdir=workdir,
            policy=AcpPolicy(mode="approve-reads"),
            prompt=(
                "First use the read tool to read the file existing.txt in the "
                "current directory and repeat its exact contents back to me. "
                "Then use the write tool to create a new file named newfile.txt "
                "with the content 'should-be-blocked'. Do not use the task tool."
            ),
            timeout=30,
        )

        assert not (workdir / "newfile.txt").exists(), (
            f"write should have been blocked (approve-reads leaves write on '*':'ask', "
            f"non-interactive default rejects); stdout tail:\n{result.stdout[-2000:]}"
        )

        raw_text = "\n".join(json.dumps(e.raw) for e in events)
        assert marker in raw_text, (
            f"expected the read tool's output to surface the existing file's content "
            f"somewhere in the event stream; stdout tail:\n{result.stdout[-2000:]}"
        )
